name: Update Blog

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Update Posts List"]
    types:
      - completed
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-blog:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r .github/scripts/requirements.txt
  
        - name: Update html for blog
          env:
            TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
          run: python .github/scripts/update_blog.py
          
